{
"name": "application",
"profiles": [
"default"
],
"label": null,
"version": "2f2254a1fdf2d09e27da3d7617de3d8d6124d9f7",
"state": null,
"propertySources": [
{
"name": "https://github.com/ShivanshShiv07/microservice-tutorial-config/application.yml",
"source": {
"spring.application.name": "Config-Dev",
"eureka.client.fetch-registry": true,
"eureka.client.register-with-eureka": true,
"eureka.client.service-url.defaultZone": "http://localhost:8761/eureka",
"eureka.instances.prefer-ip-address": true
}
}
]
}
